name: Build latest tag

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Set Node.js 14.x
      uses: actions/setup-node@master
      with:
        version: 14.x
    - name: npm install
      run: npm install
    - name: npm run build
      run: npm run build
    - name: Docker Build and Push
      uses: danubetech/github-action-docker-build-push@master
      env:
        DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        DOCKER_FILE: docker/Dockerfile
        CONTAINER_TAG: universalresolver/universal-resolver-frontend:latest
    - name: Slack notification
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,commit,action,eventName,ref,workflow
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      if: failure()
